cia-282-change-home-top-background
PipocaAgil-Grupo-Bordo/ciclo-agil-mobile pull request #141
Opened 2024-12-16 16:35 UTC by KarenLukianyAlmeida

2024-12-16 16:38 UTC, KarenLukianyAlmeida commented
Comentei os icones de configuração e notificação da pégina Home

2024-12-17 00:27 UTC, Rayandson requested changes

2024-12-17 00:27 UTC, Rayandson commented on src/pages/Home/HomeTopBackground/style.ts
> +    top: -10;
Não entendi o porque do -10 (que aliás, deveria ter uma unidade, como "px", para valores diferentes de 0). Para mim deixar como 0 funciona e acredito que fique também mais similar ao figma.

2024-12-17 00:27 UTC, Rayandson commented on src/pages/Home/HomeTopBackground/index.tsx
> +      <StatusBar style="auto" translucent />
Já que a idéia é todas as páginas (ou a maioria) terem esse comportamento da status bar ser translúcida, o que acha de movermos a StatusBar para o `PageContainer`? E aí futuramente podemos fazer com que o PageContainer aceite uma opção para desativar esse comportamento em uma página específica caso necessário.

Ficaria algo assim:
```
    <Container style={style}>
        <StatusBar style="auto" translucent />
        {children}
    </Container>
```

2024-12-17 10:14 UTC, KarenLukianyAlmeida commented on src/pages/Home/HomeTopBackground/style.ts
> +    top: -10;
Ok. Vou alterar para 0.

2024-12-17 10:17 UTC, KarenLukianyAlmeida commented on src/pages/Home/HomeTopBackground/index.tsx
> +      <StatusBar style="auto" translucent />
Boa. Fiz esta alteraçao aqui.

2024-12-17 11:56 UTC, Rayandson approved these changes

2024-12-17 15:39 UTC, merged